<<<<<<< HEAD
categories:
  - title: 'ðŸš€ Features'
    labels:
      - 'feature'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'bug'
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+'
      - '/hotfix\/.+'
      - '/bug\/.+'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES
=======
categories:
  - title: 'ðŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'bug'
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES
>>>>>>> develop
