FROM node:18-bullseye-slim as base

WORKDIR /app

# certificates config
ARG NODE_EXTRA_CA_CERTS
COPY ./cert/. /etc/ssl/certs/

# downgrade npm version to avoid chokidar error
RUN npm install -g npm@8

COPY ./package.json ./package-lock.json ./
RUN npm ci

COPY src ./src
COPY public ./public
COPY vite.config.js index.html ./

FROM base as dev

CMD ["npm", "run", "dev"]

FROM base as build

# RUN npm ci --production
RUN npm run build

FROM nginx:1.21.4-alpine as prod

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist /usr/share/nginx/html/

USER root
RUN ls
RUN grep -rlw http /etc |while read i ;do sed -ri 's#\b80\b#8080#' ${i} ; sed -ri 's#\b443\b#6443#' ${i} ;done
RUN find / -xdev -exec chmod -f -c g=u {} \; -exec chown -f -c 1001:root {} \; >/dev/null 2>&1
RUN grep -w 1001 /etc/passwd ||echo "rootless:x:1001:0:root:/root:/bin/bash" >>/etc/passwd
USER 1001
