include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  REGISTRY_URL: "${REGISTRY_HOST}/${PROJECT_PATH}"

stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build-frontend:
  variables:
    WORKING_DIR: "frontend"
    IMAGE_NAMES: basegun-frontend:${CI_COMMIT_REF_SLUG} basegun-frontend:${CI_COMMIT_SHORT_SHA}
    DOCKERFILE: "frontend/Dockerfile"
    BUILD_ARGS: --build-arg=VERSION=1.1.1
  stage: docker-build
  extends:
    - .kaniko:build-push

docker-build-backend:
  variables:
    WORKING_DIR: "backend"
    IMAGE_NAMES: basegun-backend:${CI_COMMIT_REF_SLUG} basegun-backend:${CI_COMMIT_SHORT_SHA}
    DOCKERFILE: "backend/Dockerfile"
    BUILD_ARGS: --build-arg=VERSION=1.1.1
  stage: docker-build
  extends:
    - .kaniko:build-push
