services:
  backend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - VERSION=${TAG:-latest}
        - CACERT_LOCATION
      context: ./backend
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000 --no-server-header
    container_name: basegun-backend
    environment:
      - S3_URL_ENDPOINT=http://minio:9000
      - S3_BUCKET_NAME=basegun-s3
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - http_proxy
      - https_proxy
      - no_proxy
      - REQUESTS_CA_BUNDLE=$CACERT_LOCATION
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
      - ./backend/logs:/tmp/logs

  frontend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - NODE_EXTRA_CA_CERTS=$CACERT_LOCATION
      context: ./frontend
      target: ${BUILD_TARGET:-dev}
    container_name: basegun-frontend
    ports:
      - 8080:80 # if BUILD_TARGET = prod
      - 3000:5173
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
