describe('HomePage', () => {
    it('shoud visit HomePage', () => {
      cy.visit('/')
      cy.getByDataTestid('basegun-logo').should('exist')
      cy.contains('li', 'Basegun est une application')
      cy.get('.swiper-button-next').click()
      cy.contains('li', 'Une arme doit toujours être')
      cy.get('#position-button').contains('J\'ai compris').click()
      cy.url().should('contain', '/accueil')
    })
  
  it('should open Menu informations', () => {
    cy.visit('/')
    cy.getByDataTestid('header-logo').contains('Ministère')
    cy.get('#button-menu')
      .should('exist')
      .click()
    cy.getByRole('navigation')
      .contains('a', 'A propos')
      .click()
    cy.url()
      .should('contain', '/a-propos')
    cy.get('#button-menu')
      .click()
    cy.getByRole('navigation')
      .contains('a', 'Mentions légales')
      .click()
    cy.url()
      .should('contain', '/mentions-legales')
    cy.get('#button-menu')
      .click()
    cy.getByRole('navigation')
      .contains('a', 'Contact')
      .click()
    cy.url()
      .should('contain', '/contact')
    cy.get('.information')
      .should('exist')
      .click()
    cy.url().should('contain','/')
    })
  }
)