describe('Old Mechanism Pistol Securing', () => {
  it('should secure and identificate old mechanism pistol', () => {
    cy.visit('/')
    cy.getByDataTestid('basegun-logo').should('exist')
    cy.contains('li', 'Basegun est une application')
    cy.get('swiper-container').shadow().find('.swiper-button-next').click()
    cy.contains('li', 'ne remplace en aucun cas l\'avis d\'un expert')
    cy.get('#agree-button').contains('J\'ai compris').click()
    cy.url().should('contain', '/accueil')

    cy.getByDataTestid('secure-firearm')
      .contains('Je veux mettre en sécurité mon arme')
      .click()
    cy.url().should('contain', '/guide-mise-en-securite/mise-en-securite-recommandations')
    cy.contains('h2', 'Mettre en sécurité mon arme')
    cy.contains('span', 'extraire des munitions')
    cy.getByDataTestid('button-next')
      .contains('Suivant')
      .click()
    cy.url().should('contain', '/guide-mise-en-securite/mise-en-securite-instructions')
    cy.contains('h2', 'Mettre en sécurité mon arme')
    cy.contains('span', 'DIRECTION SÛRE')
    cy.getByDataTestid('button-next')
      .contains('Suivant')
      .click()
    cy.url().should('contain', '/guide-mise-en-securite/mise-en-securite-introduction')
    cy.contains('h2', 'Mettre en sécurité mon arme')
    cy.contains('span', 'tutoriel adapté')
    cy.getByDataTestid('button-next')
      .contains('Suivant')
      .click()
    cy.getByDataTestid('select-file').as('fileInput')
    cy.intercept('POST', '/api/upload').as('upload')
    cy.get('@fileInput').selectFile('./cypress/images/pistolet-ancien-a-percussion-monocoup.jpg', { force: true })
    cy.wait('@upload').then(({ response }) => {
      expect(response.statusCode).to.eq(200)
    })
    cy.contains('h2', 'Pas de guide de mise en sécurité pour votre arme')
    cy.url().should('contain', '/fin-mise-en-securite')
    cy.getByDataTestid('go-to-identification').click()
    cy.url().should('contain', '/guide-identification/resultat-typologie')
    cy.getByDataTestid('arm-category').should('contain', 'Catégorie D')
    cy.getByDataTestid('return-to-home-end').click()
    cy.url().should('contain', '/accueil')
  })
})
