describe('Typology Revolver Securing', () => {
  it('should identificate revolver with small fireplaces (?) ', () => {
    cy.accueil()
    cy.miseEnSecurite()
    cy.getByDataTestid('select-file').as('fileInput')
    cy.intercept('POST', '/api/upload').as('upload')
    cy.get('@fileInput').selectFile('./cypress/images/revolver.jpg', { force: true })
    cy.wait('@upload').then(({ response }) => {
      expect(response.statusCode).to.eq(200)
    })
    cy.url().should('contain', '/mise-en-securite-choix-option-etape/1')
    cy.getByDataTestid('button-next').should('have.attr', 'disabled')
    cy.contains('Petites Cheminées').first().click()
    cy.getByDataTestid('button-next').should('not.have.attr', 'disabled')
    cy.getByDataTestid('button-next').click()
    cy.url().should('contain', '/fin-mise-en-securite')
    cy.contains('h2', 'mise en sécurité')
    cy.contains('p', 'les manipulations sont complexes')
    cy.getByDataTestid('go-to-identification').click()
    cy.url().should('contain', '/guide-identification/resultat-typologie')
    cy.getByDataTestid('arm-category').should('contain', 'Catégorie D')
  })

  it('should secure and identificate real revolver with barrel button', () => {
    cy.accueil()
    cy.miseEnSecurite()
    cy.getByDataTestid('select-file').as('fileInput')
    cy.intercept('POST', '/api/upload').as('upload')
    cy.get('@fileInput').selectFile('./cypress/images/revolver.jpg', { force: true })
    cy.wait('@upload').then(({ response }) => {
      expect(response.statusCode).to.eq(200)
    })
    cy.url().should('contain', '/mise-en-securite-choix-option-etape/1')
    cy.getByDataTestid('button-next').should('have.attr', 'disabled')
    cy.contains('Arrière plat').first().click()
    cy.getByDataTestid('button-next').should('not.have.attr', 'disabled')
    cy.getByDataTestid('button-next').click()
    cy.url().should('contain', '/mise-en-securite-choix-option-etape/2')
    cy.getByDataTestid('button-next').should('have.attr', 'disabled')
    cy.contains('Revolver bouton barillet').first().click()
    cy.getByDataTestid('button-next').should('not.have.attr', 'disabled')
    cy.getByDataTestid('button-next').click()
    cy.getVideo()
    cy.contains('h2', 'Mettre en sécurité mon arme')
    cy.contains('li', 'Tirer ou pousser')
    cy.getByDataTestid('button-next').click()
    cy.url().should('contain', '/fin-mise-en-securite')
    cy.Identification()
    cy.contains('balles').first().click()
    cy.getByDataTestid('next-step').click()
    cy.url().should('contain', '/guide-identification/resultat-final')
    cy.getByDataTestid('arm-category').should('contain', 'Catégorie B')
    cy.getByDataTestid('return-to-home-end').click()
    cy.url().should('contain', '/accueil')
  })
  it('should secure and identificate real revolver with hidden door', () => {
    cy.accueil()
    cy.miseEnSecurite()
    cy.getByDataTestid('select-file').as('fileInput')
    cy.intercept('POST', '/api/upload').as('upload')
    cy.get('@fileInput').selectFile('./cypress/images/revolver.jpg', { force: true })
    cy.wait('@upload').then(({ response }) => {
      expect(response.statusCode).to.eq(200)
    })
    cy.url().should('contain', '/mise-en-securite-choix-option-etape/1')
    cy.getByDataTestid('button-next').should('have.attr', 'disabled')
    cy.contains('Arrière plat').first().click()
    cy.getByDataTestid('button-next').should('not.have.attr', 'disabled')
    cy.getByDataTestid('button-next').click()
    cy.url().should('contain', '/mise-en-securite-choix-option-etape/2')
    cy.getByDataTestid('button-next').should('have.attr', 'disabled')
    cy.contains('Portière qui cache le côté droit du barillet').first().click()
    cy.getByDataTestid('button-next').should('not.have.attr', 'disabled')
    cy.getByDataTestid('button-next').click()
    cy.getByDataTestid('button-next').should('have.attr', 'disabled')
    cy.contains('Le barillet ne bascule pas').first().click()
    cy.getByDataTestid('button-next').should('not.have.attr', 'disabled')
    cy.getByDataTestid('button-next').click()
    cy.get('.fr-accordions-group > li').first().click()
    cy.getByDataTestid('button-step-mes').click({ multiple: true }, { force: true })
    cy.getByDataTestid('button-next').should('not.have.attr', 'disabled')
    cy.getByDataTestid('button-next').click()
    cy.Identification()
    cy.contains('balles').first().click()
    cy.getByDataTestid('next-step').click()
    cy.url().should('contain', '/guide-identification/resultat-final')
    cy.getByDataTestid('arm-category').should('contain', 'Catégorie B')
    cy.getByDataTestid('return-to-home-end').click()
    cy.url().should('contain', '/accueil')
  })
})
