/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AskingExpert: typeof import('./components/AskingExpert.vue')['default']
    HeaderMain: typeof import('./components/HeaderMain.vue')['default']
    OnboardingSwiper: typeof import('./components/OnboardingSwiper.vue')['default']
    ResultPage: typeof import('./components/ResultPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarAlert: typeof import('./components/SnackbarAlert.vue')['default']
    StepsGuide: typeof import('./components/StepsGuide.vue')['default']
    UploadButton: typeof import('./components/UploadButton.vue')['default']
  }
}
