/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AskingExpert: typeof import('./components/AskingExpert.vue')['default']
    ContactExpert: typeof import('./components/ContactExpert.vue')['default']
    DsfrAccordion: typeof import('@gouvminint/vue-dsfr')['DsfrAccordion']
    DsfrAccordionsGroup: typeof import('@gouvminint/vue-dsfr')['DsfrAccordionsGroup']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrBadge: typeof import('@gouvminint/vue-dsfr')['DsfrBadge']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrCheckbox: typeof import('@gouvminint/vue-dsfr')['DsfrCheckbox']
    DsfrFileUpload: typeof import('@gouvminint/vue-dsfr')['DsfrFileUpload']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrInputGroup: typeof import('@gouvminint/vue-dsfr')['DsfrInputGroup']
    DsfrModal: typeof import('@gouvminint/vue-dsfr')['DsfrModal']
    DsfrPicture: typeof import('@gouvminint/vue-dsfr')['DsfrPicture']
    DsfrRadioButton: typeof import('@gouvminint/vue-dsfr')['DsfrRadioButton']
    DsfrRadioButtonSet: typeof import('@gouvminint/vue-dsfr')['DsfrRadioButtonSet']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrTag: typeof import('@gouvminint/vue-dsfr')['DsfrTag']
    FooterMES: typeof import('./components/FooterMES.vue')['default']
    HeaderMain: typeof import('./components/HeaderMain.vue')['default']
    OnboardingSwiper: typeof import('./components/OnboardingSwiper.vue')['default']
    PopupContact: typeof import('./components/PopupContact.vue')['default']
    PopupVideo: typeof import('./components/PopupVideo.vue')['default']
    ResultPage: typeof import('./components/ResultPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarAlert: typeof import('./components/SnackbarAlert.vue')['default']
    StepsGuide: typeof import('./components/StepsGuide.vue')['default']
    UploadButton: typeof import('./components/UploadButton.vue')['default']
    VIcon: typeof import('oh-vue-icons')['OhVueIcon']
  }
}
