export {
  RiCameraFill,
  RiCameraLine,
  RiMenuFill,
  RiThumbDownLine,
  RiThumbUpLine,
  RiThumbUpFill,
  RiThumbDownFill,
  RiZoomInLine,
  RiArrowGoBackFill,
  RiMailLine,
  RiErrorWarningLine,
  RiAlertLine,
  RiArrowLeftLine,
  RiArrowRightLine,
  RiListOrdered,
  RiLogoutBoxRLine,
  RiInformationFill,
  RiInformationLine,
  RiHome3Line,
  RiHome4Line,
  RiCheckboxCircleLine,
} from 'oh-vue-icons/icons/ri/index.js'
