export {
  RiCameraFill,
  RiCameraLine,
  RiMenuFill,
  RiThumbDownLine,
  RiThumbUpLine,
  RiThumbUpFill,
  RiThumbDownFill,
  RiZoomInLine,
  RiArrowGoBackFill,
  RiListOrdered,
  RiLogoutBoxRLine,
  RiInformationFill,
  RiHome3Line,
} from 'oh-vue-icons/icons/ri/index.js'
